const FULL_NAME_LENGTH = 6;
const ACCOUNT_INITIAL_VALUE = 0.00;
const CPF_INITIAL_POSITION = 3;
const CPF_END_POSITION = 12;
const NUMBERS_DECIMAL_PLACES = 2;
const PARSE_INT_RADIX = 10;
const PASSWORD_LENGTH = 10;
const TRANSACTIONS_MAXIMUM_VALUE = 2000;

module.exports = {
  FULL_NAME_LENGTH,
  ACCOUNT_INITIAL_VALUE,
  CPF_INITIAL_POSITION,
  CPF_END_POSITION,
  NUMBERS_DECIMAL_PLACES,
  PARSE_INT_RADIX,
  PASSWORD_LENGTH,
  TRANSACTIONS_MAXIMUM_VALUE,
};